title: Medical Image Analysis Laboratory
description: This is the home page for the MIA Lab at Uni Bern.
theme: just-the-docs

url: https://ubern-mialab.github.io/ubern-mialab

aux_links:
  Template Repository: https://github.com/ubern-mialab/ubern-mialab
